name: Passing Data Demo

on: [push, workflow_dispatch]

jobs: 
    build:
      runs-on: ubuntu-latest
      outputs:
        version: ${{ steps.setver.outputs.ver }}
      steps:
        - name: Set Version Tag
          id: setver
          run: echo "ver=v1.0.${{ github.run_number }}" >> $GITHUB_OUTPUT

    deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Use Version Tag
          run: echo "Deploying version ${{ needs.build.outputs.version }}"