name: Conditional Demo

on: [push, workflow_dispatch]

jobs: 
    test:
      runs-on: ubuntu-latest
      steps:
        - run: echo "Running tests"

    deploy:
      runs-on: ubuntu-latest
      needs: test
      if: github.ref == 'refs/heads/main'
      steps:
        - run: echo "Deploying only from main branch"