name: Matrix Practice

on: [push, workflow_dispatch]

jobs: 
    test-matrix:
      runs-on: ubuntu-latest
      
      strategy:
        matrix:
          node-version: [14, 20]
    
      steps:
        - name: Show version
          run: echo "Testing on Node.js version ${{ matrix.node-version }}"