name: Trigger Practice

on: 
  push:
    branches: [main]
  workflow_dispatch:  

jobs: 
  show_info: 
    runs-on: ubuntu-latest

    steps:
      - name: Show basic info
        run: |
          echo "This was pushed to: ${{ github.ref }}"
          echo "Triggered by: ${{ github.actor }}"
          echo "Commit message: ${{ github.event.head_commit.message }}"