name: Use Actions

on: [push, workflow_dispatch]

jobs: 
    show-secret:
      runs-on: ubuntu-latest
      
      steps:
        - name: Print secret to log (DO NOT do this in real life!)
          uses: echo "My secret is ${{ secrets.SUPER_SECRET }}"
