name: Use Actions

on: [push, workflow_dispatch]

jobs: 
    custom-action-job:
      runs-on: ubuntu-latest
      
      steps:
        - name: Step 1 - Checkout Repo Code
          uses: actions/checkout@v4

        - name: Step 2 - Use my custom action
          uses: ./.github/actions/whoami
