name: Use Actions

on: [push, workflow_dispatch]

jobs: 
    use-actions:
      runs-on: ubuntu-latest
      
      steps:
        - Step 1: 
            name: Setup Node.js
            uses: actions/setup-node@v4

        - Step 2: 
            name: Setp Node.js
            uses: actions/setup-node@v4
            with:
              node-version: 20

        - Step 3: 
            name: Show node version
            run: node -v