name: Use Actions

on: [push, workflow_dispatch]

jobs: 
    custom-action-job:
      runs-on: ubuntu-latest
      
      steps:
        - name: checkout composite action
          uses: actions/checkout 
          
        - name: Use my custom action
          uses: ./.github/actions/whoami
