name: Use Actions

on: [push, workflow_dispatch]

jobs: 
    custom-action-job:
      runs-on: ubuntu-latest
      
      steps:
        - name: Use my custom action
          uses: ./.github/actions/whoami
