name: Runner Practice

on: [push, workflow_dispatch]

jobs: 
    runs-on-windows:
      runs-on: windows-latest
      steps:
        - name: Say hi from Windows 
          run: echo "Running on a windows machine"
    
    runs-on-linux:
      runs-on: ubuntu-latest
      steps:
        - name: Say hi from Linux
          run: echo "Running on a Linux machine"